site_name: OpenCloudOS Documentation

theme:
  name: material
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/logo.svg

nav:
  - 首页: index.md
  - 快速入门:
    - 下载: quickstart/download.md
    - 安装: quickstart/install.md
    - 使用说明: quickstart/use.md
  - 用户指南:
    - 系统管理: guide/sysadmin.md
    - 基础配置: guide/config.md
    - 更新: guide/update.md
    - 系统状态监控: guide/monitor.md
    - 安全加固: guide/security.md
    - 网络管理: guide/network.md
    - 存储管理: guide/storage.md
    - 如意QoS用户指南: guide/rui.md
  - 版本说明:
    - v8.5: release/v8.5.md
    - v8.6: release/v8.6.md
    - OpenCloudOS Stream: release/ocs.md
    - OpenCloudOS Stream Kernel: release/ocsk.md
  - 常见问题: faq.md
  - 如何贡献: contribute.md
